Enable linked multiple flexible GPUs to VM
outscale/terraform-provider-outscale pull request #277
Opened 2023-01-13 13:10 UTC by outscale-toa

fixes #220

2023-01-17 14:12 UTC, FredericBerot-Armand requested changes
I think it's better to remove ForceNew and add update function, to not unlink then link a gpu on the same update.

2023-01-23 15:23 UTC, outscale-toa commented
> I think it's better to remove ForceNew and add update function, to not unlink then link a gpu on the same update.
Done :)

2023-01-24 08:49 UTC, FredericBerot-Armand approved these changes

2024-02-23 15:42 UTC, outscale-toa commented
Merge in #409

2024-02-23 15:42 UTC, closed without merging