Enable adding tags on bsu
outscale/terraform-provider-outscale pull request #340
Opened 2023-04-14 15:29 UTC by outscale-toa

2023-04-21 09:54 UTC, outscale-mgo requested changes

2023-04-21 09:54 UTC, outscale-mgo commented on outscale/resource_outscale_vm_test.go
> +			tags {
I think this need to be set in the BSU :).

2023-04-27 14:54 UTC, outscale-mgo approved these changes

2024-02-23 15:25 UTC, outscale-toa commented
Merge in #409

2024-02-27 15:50 UTC, outscale-mgo commented on outscale/resource_outscale_vm.go
> +			ForceStop: oscgo.PtrBool(true),
Maybe there should be a way to clean stop

2024-02-27 15:50 UTC, outscale-mgo commented on outscale/resource_outscale_vm.go
> +		return fmt.Errorf("Error Froce stopping vms before destroy %s", err)
that message is weird.
also "s/Froce/Force/"

2024-02-28 08:48 UTC, merged