Update Readme for Migration to provider v1.0.0
outscale/terraform-provider-outscale pull request #449
Opened 2024-05-30 16:19 UTC by outscale-toa

2024-05-31 14:12 UTC, outscale-mgo requested changes

2024-05-31 14:12 UTC, outscale-mgo commented on README.md
> +> Before you begin using the ```v1``` binary on your Terraform code, make sure to back up your state file. If you are using a local state file, you can simply make a copy of your terraform.tfstate fi
> Before you begin using the ```v1``` binary on your Terraform code, make sure to back up your state file. If you are using a local state file, you can simply make a copy of your terraform.tfstate file in your project directory.
 
I would split that line, so we can see the part about backuping stuff better.
 
  > Before you begin using the ```v1``` binary on your Terraform code, make sure to back up your state file. 
  > If you are using a local state file, you can simply make a copy of your terraform.tfstate file in your project directory.

2024-05-31 14:12 UTC, outscale-mgo commented on README.md
> +> If you are using a remote backend such as an S3 bucket, make sure that you follow the backup procedures for the backend and that you exercise the restore procedure at least once.
> If you are using a remote backend such as an S3 bucket, make sure that you follow the backup procedures and that you exercise the restore procedure at least once.

2024-05-31 14:12 UTC, outscale-mgo commented on README.md
> +
can you explain with a few small line, what the sed are doing, pelase.

2024-06-19 09:38 UTC, outscale-hmi commented on CHANGELOG.md
> +IMPROVEMENT:
IMPROVEMENTS*:

2024-06-19 09:38 UTC, outscale-hmi commented on CHANGELOG.md
> +* Somes refactoring
Some*

2024-06-19 09:38 UTC, outscale-hmi commented on README.md
> +> If you are using a local state file, you can just copy of your terraform.tfstate file in your project directory.
you can just copy or make copy of **

2024-06-19 09:38 UTC, outscale-hmi commented on README.md
> +Somes block types changed in terraform state, the following script will delete those blocks.
Some* block types changed in the Terraform state. The following script will delete those blocks.

2024-06-19 10:00 UTC, outscale-hmi approved these changes

2024-06-19 12:13 UTC, outscale-rce approved these changes

2024-06-19 12:14 UTC, outscale-rce approved these changes

2024-06-19 12:16 UTC, outscale-mdr approved these changes

2024-06-20 08:14 UTC, outscale-mgo approved these changes

2024-06-20 09:12 UTC, merged